// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKwA2DdASQgpvKom2uJx9JPs8GwDeGOtw',
    appId: '1:224159145866:web:a3efe5a12cddf42350b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    authDomain: 'social-media-app-c75f9.firebaseapp.com',
    storageBucket: 'social-media-app-c75f9.appspot.com',
    measurementId: 'G-2J1HP8L467',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mP8oUwjn3g4e7sx5sae4NLGn-uKLpy4',
    appId: '1:224159145866:android:632714599e0a046550b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    storageBucket: 'social-media-app-c75f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU6UR_x8YO2BL1_AWpNjR0RyGbT5XcWZ0',
    appId: '1:224159145866:ios:42c55b45942cbbc750b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    storageBucket: 'social-media-app-c75f9.appspot.com',
    iosBundleId: 'com.example.mySocialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU6UR_x8YO2BL1_AWpNjR0RyGbT5XcWZ0',
    appId: '1:224159145866:ios:a4e7bf8ba5fd133e50b273',
    messagingSenderId: '224159145866',
    projectId: 'social-media-app-c75f9',
    storageBucket: 'social-media-app-c75f9.appspot.com',
    iosBundleId: 'com.example.mySocialmedia.RunnerTests',
  );
}
